info:
  name: List available advisors for student loan application
  type: http
  seq: 1
  tags:
    - Student_loans

http:
  method: GET
  url: "{{baseUrl}}/student/advisors"
  headers:
    - name: cmu_session
      value: "{{apiKey}}"
  auth:
    type: apikey
    key: cmu_session
    value: "{{apiKey}}"
    placement: header

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: true

examples:
  - name: 200 Response
    description: Successful response
    request:
      url: "{{baseUrl}}/student/advisors"
      method: GET
      headers:
        - name: cmu_session
          value: "{{apiKey}}"
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: ""
  - name: 401 Response
    description: Unauthorized
    request:
      url: "{{baseUrl}}/student/advisors"
      method: GET
      headers:
        - name: cmu_session
          value: "{{apiKey}}"
    response:
      status: 401
      statusText: Unauthorized
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "error": {
              "code": "",
              "message": ""
            }
          }
  - name: 500 Response
    description: Internal Server Error
    request:
      url: "{{baseUrl}}/student/advisors"
      method: GET
      headers:
        - name: cmu_session
          value: "{{apiKey}}"
    response:
      status: 500
      statusText: Internal Server Error
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "error": {
              "code": "",
              "message": ""
            }
          }
